### ISSUE TITLE
INFOGRAFIA: CALIDAD DE SOFTWARE

### ISSUE THREAD

**Issue by Rmz-Rigo** [SistemasTecTlaxiaco/infografia-de-calidad-remi#1]
[INF CALIDAD DE SOFTWARE_RIGOBERTORMZNICOLAS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-calidad-remi/files/8767274/INF.CALIDAD.DE.SOFTWARE_RIGOBERTORMZNICOLAS.pdf)

**Comment by Abraham890** [comment]
Calificacion: 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
