### ISSUE TITLE
Infografía - Calidad de software.

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/infografia-de-calidad-remi#3]
[Infografía - Calidad de Software.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-calidad-remi/files/8794375/Infografia.-.Calidad.de.Software.pdf)

**Comment by Sandra631** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
